### ISSUE TITLE
[Feature] Add an option for users to select Pinia or VueX as a default state management

### ISSUE THREAD

**Issue by ThinhVu** [bluwy/create-vite-extra#1]
It's better to have a step that users can select:
- Default: Don't include state management
- Pinia: Using Pinia as the default store
- VueX: Using VueX as the default store

**Comment by bluwy** [comment]
I think I'd want to keep the templates closer to Vite-only features + X framework for now. So framework-land libraries like pinia, vue-router, etc, shouldn't be kept here. It's also a bit hard to maintain this matrix with how the templates are setup now.

I believe pinia is the recommended approach moving forward too, and `npm create vue` covers it.
