### ISSUE TITLE
Cannot select template

### ISSUE THREAD

**Issue by idanran** [bluwy/create-vite-extra#15]
![image](https://user-images.githubusercontent.com/96647698/202740949-2e91203c-571a-46b6-89be-aababf82b2b5.png)
Unable to move up and down.
OS version: Windows 11 22H2

**Comment by bluwy** [comment]
Does this happen with `npm create vite-extra@latest`? I wonder if Deno is somehow messing with it. And also maybe try `npm create vite@latest`. It could be a problem with the `prompts` package. It might also be an issue with the terminal you're using too.

**Comment by idanran** [comment]
> Does this happen with `npm create vite-extra@latest`? I wonder if Deno is somehow messing with it. And also maybe try `npm create vite@latest`. It could be a problem with the `prompts` package. It might also be an issue with the terminal you're using too.

`npm create vite-extra@latest` is normal

**Comment by idanran** [comment]
![image](https://user-images.githubusercontent.com/96647698/202847103-6c3920d8-8848-445f-9aa0-f42becbdbfaf.png)
The same problem occurs with cmd.

**Comment by bluwy** [comment]
Thanks for testing this. It seems to be a compatibility issue with Deno + prompts + Windows then. It works fine for me on macos. You could report this to https://github.com/denoland/deno/issues about this.

**Comment by idanran** [comment]
> Thanks for testing this. It seems to be a compatibility issue with Deno + prompts + Windows then. It works fine for me on macos. You could report this to https://github.com/denoland/deno/issues about this.

ok

**Comment by bluwy** [comment]
Closing this for now as it's an upstream issue.
