### ISSUE TITLE
EPERM: operation not permitted, readdir

### ISSUE THREAD

**Issue by justinfriebel** [bluwy/create-vite-extra#17]
Any ideas on why I can't run this? I updated node and the npm global install to latest LTS versions and tried a few other things.

```
~/projects/deno-solid
❯ deno task dev
Task dev deno run -A --node-modules-dir npm:vite
error when starting dev server:
Error: EPERM: operation not permitted, readdir
    at __node_internal_captureLargerStackTrace (https://deno.land/std@0.165.0/node/internal/errors.ts:113:11)
    at __node_internal_uvException (https://deno.land/std@0.165.0/node/internal/errors.ts:250:10)
    at denoErrorToNodeError (https://deno.land/std@0.165.0/node/internal/errors.ts:2500:14)
    at https://deno.land/std@0.165.0/node/_fs/_fs_readdir.ts:75:16
```

**Comment by bluwy** [comment]
What version of Deno and OS are you using? There was a change in the Deno templates recently that removes the `--unstable` flag, but requires the latest Deno version. (Though -A should cover it 🤔 )

It's working fine for me locally. Deno 1.28.0. macos 13

**Comment by justinfriebel** [comment]
```
❯ deno --version
deno 1.28.1 (release, x86_64-apple-darwin)
v8 10.9.194.1
typescript 4.8.3
```

MacOS 10.14.6, so maybe it's just old 🤔

**Comment by justinfriebel** [comment]
I updated MacOS but it's still happening :(.

```
npm@8.19.2 nvm/versions/node/v18.12.1
```

**Comment by bluwy** [comment]
Wow didn't expect you to do that 😅 I'm not sure what's wrong either. Just to confirm, does this only happen with the Deno template?

**Comment by bluwy** [comment]
Closing this for now. I think it's likely an issue with the filesystem permission setup, or Deno.
