### ISSUE TITLE
deno-lit-ts doesn't work

### ISSUE THREAD

**Issue by ff2400t** [bluwy/create-vite-extra#19]
Deno version used was 1.28.3

`deno task dev` throws the following error in the browser console
Error for Firefox is `Loading module from “http://localhost:5173/src/my-element.js” was blocked because of a disallowed MIME type (“”)`
Error for Chrome is `GET http://localhost:5173/src/my-element.js net::ERR_ABORTED 404 (Not Found)`

`deno task build` just fails and gives the following error in the terminal
Could not resolve entry module "src/my-element.js".
error during build
RollupError: Could not resolve entry module "src/my-element.js".`

**Comment by bluwy** [comment]
Fixed in v1.0.1. I forgot to reconfigure the JS stuff to TS.
