### ISSUE TITLE
[deno-react-ts-swc] unstable flag must be provided when running dev task

### ISSUE THREAD

**Issue by john-mirage** [bluwy/create-vite-extra#20]
## Environment
- Ubuntu 22.04.1 LTS (WSL)
- deno 1.28.3
- v8 10.9.194.5
- typescript 4.8.3

## Step to reproduce
- Create project using `deno run -A npm:create-vite-extra`
  - Enter a project name
  - Choose deno-react
  - Choose Typescript + SWC
- Go to the created directory
- run `deno task dev`

## Output
```
Task dev deno run -A --node-modules-dir npm:vite
Unstable API 'node-api'. The --unstable flag must be provided.
```

## Tests
The deno-react-ts template (without swc) works fine in my environment.

**Comment by bluwy** [comment]
Fixed in v1.0.1. Thanks for the heads up!
