### ISSUE TITLE
why Unsupported scheme "npm" for module "npm:create-vite-extra". Supported schemes: [     "data",     "blob",     "file",     "http",     "https", ]

### ISSUE THREAD

**Issue by checkwoodson** [bluwy/create-vite-extra#22]
![image](https://user-images.githubusercontent.com/33786022/209931137-a0a407d0-03f1-49b1-93d5-d9b91ae873f4.png)

i don't know why error :Unsupported scheme "npm" for module "npm:create-vite-extra". Supported schemes: [
    "data",
    "blob",
    "file",
    "http",
    "https",
]
Does deno not support npm?

**Comment by bluwy** [comment]
It does. Make sure you're using the latest version of Deno when running the command.

**Comment by bluwy** [comment]
Specifically 1.28.0 for now until https://github.com/bluwy/create-vite-extra/issues/21 is resolved.

**Comment by checkwoodson** [comment]
> Specifically 1.28.1 for now until #21 is resolved.
I had to update deno. no problem. thank you!!
