### ISSUE TITLE
Error: ENOENT: no such file or directory, open './dist/client/ssr-manifest.json'

### ISSUE THREAD

**Issue by BuptStEve** [bluwy/create-vite-extra#38]
https://vitejs.dev/guide/migration.html#manifest-files-are-now-generated-in-vite-directory-by-default

**Comment by borzaka** [comment]
Can you push the new version to NPM which includes this fix?

It's still on 2.0.0

https://www.npmjs.com/package/create-vite-extra

**Comment by bluwy** [comment]
Ah sorry about that. I thought I released it a few weeks ago. I'll get to publishing it when I get to my laptop in 4 days time.

**Comment by bluwy** [comment]
v2.0.1 published now 👍
