### ISSUE TITLE
Add Remix Template with Vite Support for Node/Deno Environments

### ISSUE THREAD

**Issue by roonie007** [bluwy/create-vite-extra#40]
Remix now works with Vite (since version 2.2.0, see [here](https://remix.run/blog/remix-heart-vite)). Can we add a Remix template for Node.js and Deno projects that use Vite? This would help people start new projects more easily.

**Comment by bluwy** [comment]
I'm happy to add Remix templates, however it seems like they're maintaining it at `remix-run/remix/templates/unstable-vite`, e.g. this is what they recommend currently (https://remix.run/docs/en/main/future/vite#getting-started):

> `npx create-remix@latest --template remix-run/remix/templates/unstable-vite`

To avoid duplicating work and potentially containing outdated template (especially that the Vite version is still actively developed), I think it's better to keep to `create-remix` for now. In the long term, I think `create-remix` can also be linked from `create-vite` as well, same as how `create-vue` and `create-svelte` exists there today.
