### ISSUE TITLE
Style flickering during SSR in development mode in template-ssr-react-streaming-ts template.

### ISSUE THREAD

**Issue by korbinzhao** [bluwy/create-vite-extra#55]
When using the template-ssr-react-streaming-ts, I encountered an issue where the page styles flicker in development mode due to SSR content being rendered before the style files. How should this be resolved?

![iShot_2024-07-18_10 12 46](https://github.com/user-attachments/assets/c4c6fc3c-5586-4635-aac2-492de98ac95e)

**Comment by bluwy** [comment]
This is expected with Vite's CSS handling (even in an SPA setup), as modules are loaded lazily and CSS may be loaded after. Many metaframeworks are able to mitigate this though by crawling the entrypoint (in this case `entry-server.tsx`) and detect all the CSS, and then inline them into the initial HTML. There's more information at https://github.com/vitejs/vite/issues/16515.

While the template could add some code to prevent the FOUC, I prefer to keep it as minimal as possible as a start. Perhaps when Vite can expose an API to make the crawling simpler, the template could use it to prevent this issue.

**Comment by romatou** [comment]
I'm experiencing the same problem! Before switching from CSS-in-JS to CSS Modules, I solved this **FOUC**, but now I have to deal with it again. Has anyone come up with a solution?
