### ISSUE TITLE
How to Deploy React SSR with TS on Vercel?

### ISSUE THREAD

**Issue by rutvik106** [bluwy/create-vite-extra#56]
I have cloned this project https://github.com/bluwy/create-vite-extra/tree/master/template-ssr-react-ts and now trying to deploy it on Vercel. But it is not working on Vercel.

What needs to be done or configured to make this SSR project run on Vercel? Or should I shift the project from Vercel to somewhere else?

Thank you.

**Comment by bluwy** [comment]
The SSR setup is a normal NodeJS server (using express) that you can start up with `node server.js` after you've run `vite build` to build the files. Perhaps https://vercel.com/guides/using-express-with-vercel helps? Any deployment platform that can run your site with a NodeJS server will do.
