### ISSUE TITLE
[Question] How does the render function in `entry-server.tsx` use the `_ssrManifest` file?

### ISSUE THREAD

**Issue by YPCrumble** [bluwy/create-vite-extra#57]
Thank you for building these examples! They're really useful.

I have a question regarding setting up SSR with Vite and React. I'm seeing code like this in `src/entry-server.tsx`, for instance in the template for React/TypeScript/streaming:

```
import React from 'react'
import { type RenderToPipeableStreamOptions, renderToPipeableStream } from 'react-dom/server'
import App from './App'

export function render(_url: string, _ssrManifest?: string, options?: RenderToPipeableStreamOptions) {
  return renderToPipeableStream(
    <React.StrictMode>
      <App />
    </React.StrictMode>,
    options
  )
}
```

What I'm trying to figure out is, how does Vite actually apply the code splitting shown in the SSR manifest file into the template? It appears that this parameter isn't used.

**Comment by bluwy** [comment]
The docs link to https://github.com/vitejs/vite-plugin-vue/blob/main/playground/ssr-vue/src/entry-server.js as an example. I think in practice, only Vue supports that specific feature and can provide that metadata? I don't know if any other frameworks have the same capability so it some cases it might not be possible to do so too.

**Comment by eric-net** [comment]
In a server-side rendering (SSR) setup with Vite and React, handling code splitting and applying it effectively involves a few steps
``` js
import { readFileSync } from 'fs'
import { join } from 'path'
import { renderToPipeableStream } from 'react-dom/server'
import App from './App'

const manifestPath = join(__dirname, 'path/to/ssr-manifest.json')
const manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'))

export function render(url: string) {
  const { scripts } = manifest[url] || { scripts: [] }
  
  // Your logic to include scripts in the HTML output
  // This could be part of the response generation where you construct the final HTML
  
  return renderToPipeableStream(
    <React.StrictMode>
      <App />
    </React.StrictMode>,
    {
      // Options for rendering
      onShellReady() {
        // Your logic here
      },
      onError(err) {
        // Your error handling
      }
    }
  )
}

```

**Comment by bluwy** [comment]
I'll close this for now as I think the question has been answered. I'm open for a PR that can showcase a simplified manifest usage across all frameworks, but for now I don't think it's crucial to have it.
