### ISSUE TITLE
Cannot build the deno-lit template

### ISSUE THREAD

**Issue by gmosx** [bluwy/create-vite-extra#7]
Thank you for providing the `deno-lit` template.

I would like to report an issue though. When I am trying to build the example, with:

```sh
deno task built
```

I get:

```
Name in package.json is required if option "build.lib.fileName" is not provided.
error during build:
Error: Name in package.json is required if option "build.lib.fileName" is not provided.
````

**Comment by bluwy** [comment]
Ah looks like that option would be required in Vite as Deno doesn't have `package.json`. Adding that one.

**Comment by bluwy** [comment]
Oh ya lit projects with vite don't really have a `serve` or `preview` command as it's using Vite's library mode feature. I guess we should remove that to avoid confusion. Here's Vite's template too: https://github.com/vitejs/vite/blob/7c4accb8dec3204948d7b73e5386e789661f9198/packages/create-vite/template-lit/package.json#L15
