### ISSUE TITLE
The deno-lit template ignores the import_map.json mappings.

### ISSUE THREAD

**Issue by gmosx** [bluwy/create-vite-extra#8]
The vite setup used in the `deno-lit` template ignores mappings defined in the deno `import_map.json` file.
Supporting this would be a fantastic DX enhancement.

**Comment by bluwy** [comment]
I think this supported through a Vite plugin rather than a template. FWIW Vite doesn't have support for `package.json` import maps too. Closing as this is out of scope of the repo.
